name: mod-gmdmar-monthly.yml | Last month of mods to gmd.mar, in gmdmar-recent-monthly/
on:
  push: 
    branches: master
  schedule:
    - cron: '08 4 1 * *' #offset from UTC to ensure that "today" is in the correct month

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Set LASTMONTH env
        run: echo "LASTMONTH=$(date -d "-$(date +%d) days" "+%Y%m")" >> $GITHUB_ENV
      - name: Set FIRSTDAYLASTMONTH env
        run: echo "FIRSTDAYLASTMONTH=$(date -d "-1 month -$(($(date +%d)-1)) days" +"%Y-%m-%d")" >> $GITHUB_ENV
      - name: Set LASTDAYLASTMONTH env
        run: echo "LASTDAYLASTMONTH=$(date -d "-$(date +%d) days" "+%Y-%m-%d")" >> $GITHUB_ENV
  
      - name: Fetch API Data - ${{ env.LASTMONTH }}ðŸ“¦
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://www.loc.gov/search/?all=true&sb=shelf-id&sq=group:gmd.mar+AND+number_source_modified:[${{ env.FIRSTDAYLASTMONTH }} TO ${{ env.LASTDAYLASTMONTH }}]&fo=json&at=facets
          RETRY: true
          SAVE_NAME: gmdmar-mod-monthly-${{ env.LASTMONTH }}
          
      - name: Fetch API Data - THISMONTHðŸ“¦
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://www.loc.gov/search/?all=true&sb=shelf-id&sq=group:gmd.mar+AND+number_source_modified:[${{ env.FIRSTDAYLASTMONTH }} TO ${{ env.LASTDAYLASTMONTH }}]&fo=json&at=facets
          RETRY: true
          SAVE_NAME: maps-loc-gov-facets-THISMONTH
          
      - name: Build and Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.BUILD_AND_DEPLOY_ACTION_ACCESS_TOKEN }}
          BRANCH: master # Pushes the updates to the master branch.
          FOLDER: fetch-api-data-action # Must maintain this variable, appears to be ignored
          TARGET_FOLDER: docs/_data/gmdmar-recent-monthly # Saves the data into the 'docs/_data' directory on the master branch.
          CLEAN: false
