name: sanbornfacets.yml | Get current facets for loc.gov/collections/sanborn-maps
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Set env
        run: echo "TIMESTAMP=$(date +"%Y%m%d")" >> $GITHUB_ENV
  
      - name: Fetch API Data -${{ env.TIMESTAMP }}ðŸ“¦
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://www.loc.gov/collections/sanborn-maps/?at=facets&fo=json
          RETRY: true
          SAVE_NAME: sanborn-facets-${{ env.TIMESTAMP }}
          
      - name: Fetch API Data - TODAYðŸ“¦
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://www.loc.gov/collections/sanborn-maps/?at=facets&fo=json
          RETRY: true
          SAVE_NAME: sanborn-facets-TODAY
          
      - name: Build and Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.BUILD_AND_DEPLOY_ACTION_ACCESS_TOKEN }}
          BRANCH: master # Pushes the updates to the master branch.
          FOLDER: fetch-api-data-action # Must maintain this variable, appears to be ignored
          TARGET_FOLDER: docs/_data/sanborn-facets-daily # Saves the data into the 'docs/_data/sanborn-facets-daily' directory on the master branch.
          CLEAN: false
